// scripts/hint-cases.mjs — test wishes for scripts/eval-hints.mjs
// [wish line, word stems that would give the item away]
export const CASES = [
  ["needs: Nike Pegasus running shoes size 42", ["shoe","sneaker","trainer","nike","pegasus","footwear"]],
  ["wants: Nike long socks", ["sock","nike"]],
  ["craves: JBL Boombox 4", ["speaker","jbl","boombox","stereo"]],
  ["craves: Haribo candy", ["candy","candies","gumm","haribo","jelly"]],
  ["Kindle Paperwhite", ["kindle","e-reader","ereader","reader","tablet"]],
  ["Sony WH-1000XM5 headphones", ["headphone","earphone","sony","noise-cancel","noise cancel"]],
  ["Lego Technic Porsche 911", ["lego","brick","porsche","building set","model car"]],
  ["wants: Le Creuset Dutch oven in blue", ["pot","dutch oven","casserole","creuset","cast-iron","cast iron","cookware"]],
  ["Dyson Airwrap", ["dryer","styler","dyson","airwrap","curl"]],
  ["Chanel No. 5 perfume", ["perfume","fragrance","scent","chanel","cologne"]],
  ["dreams of: Coldplay concert tickets", ["ticket","concert","coldplay"]],
  ["massage voucher", ["massage","voucher","spa"]],
  ["Harry Potter illustrated edition", ["book","harry","potter","novel","edition"]],
  ["PS5 DualSense controller, white", ["controller","gamepad","ps5","playstation","dualsense","console"]],
  ["Patagonia fleece jacket size M", ["fleece","jacket","patagonia","coat"]],
  ["Moleskine notebook", ["notebook","journal","moleskine","diary"]],
  ["Aeropress coffee maker", ["coffee maker","aeropress","brewer","press"]],
  ["needs: Garmin Forerunner 265", ["watch","garmin","forerunner","tracker"]],
  ["a cooking class", ["cooking class","class","course","lesson"]],
  ["Manduka yoga mat", ["mat","manduka"]],
  ["potrebujem: nove tekaške copate Asics", ["shoe","sneaker","trainer","asics","copat","footwear"]],
  ["želim si: AirPods", ["airpod","earbud","headphone","earphone","apple"]],
  ["rada imam: Milka čokolado", ["chocolate","milka","cokolad","čokolad"]],
  ["knjiga: Alamut, Vladimir Bartol", ["book","alamut","bartol","novel"]],
  ["termovka Stanley 1L", ["thermos","flask","bottle","stanley","tumbler"]],
  ["vikend v toplicah", ["spa","thermal","toplic","wellness"]],
  ["is into: photography", []],
  ["dreams of: a trip to Japan", ["japan","tokyo","kyoto"]],
  ["needs: warm winter gloves size L", ["glove","mitten"]],
  ["nekaj za vrt", []]
];
